### PR TITLE
NO-TICKET Create some compliance-triggering files

### PR DESCRIPTION
**Pull request by mhughesacn**
Don't merge these test changes

### CODE REVIEW

**Comment by mhughesacn** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/martin.hughes/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](http://broken.url)

**Comment by mhughesacn** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/martin.hughes/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](http://invalid.url)

**Comment by mhughesacn** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/martin.hughes/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](http://invalid.url)

**Comment by mhughesacn** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/martin.hughes/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](http://invalid.url)

**Comment by mhughesacn** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/martin.hughes/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](http://invalid.url)

**Comment by mhughesacn** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/martin.hughes/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](http://invalid.url)

**Comment by ColumOD** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/colum.odonovan/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](http://invalid.url)

**Comment by ColumOD** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/colum.odonovan/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](http://invalid.url)

**Comment by ColumOD** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/colum.odonovan/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](http://invalid.url)

**Comment by ColumOD** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/colum.odonovan/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](https://gist.github.com/d33ac786aafde92de723d2428155b746)

**Comment by ColumOD** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/colum.odonovan/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](https://gist.github.com/6ff08118ce74d5d6b69fb3304e1de8da)

**Comment by ColumOD** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/colum.odonovan/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](https://gist.github.com/39b5d221f6c990af8cf27d398b64ce32)

**Comment by ColumOD** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/colum.odonovan/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](https://gist.github.com/c5f66468f2e8cf063f890ce0160e4c0d)

**Comment by ColumOD** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/colum.odonovan/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](https://gist.github.com/5a4c30605854ababadd2e9fc881c8208)

**Comment by ColumOD** [comment]
## Copyright scan failure
 **Commit:** 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab
**Report detail:**  https://gist.github.com/e4c5189e8a3f888fbc8e14fa461d75c5

**Comment by ColumOD** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/colum.odonovan/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](https://gist.github.com/7a8c1413b4465718816d18ef830df13e)

**Comment by ColumOD** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/colum.odonovan/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](https://gist.github.com/e272b5743bcedab59a29ed1046a16992)

**Comment by ColumOD** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 3 files pending identification.
* Protex Server Path: /Users/colum.odonovan/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 5ba12b59f3af6883a5b2cc4d0b7026a7fa691eab

 **Report detail:** [gist](https://gist.github.com/5ff71ed0b90f8ad3317db73186dc0ab9)

**Comment by mhughesacn** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 5 files pending identification.
* Protex Server Path: /Users/martin.hughes/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 1cf11562d591fd5e4a60bcf708426aa3f2493293

 **Report detail:** [gist](https://gist.github.com/b8f5144a342adf5eb2b1e486f0b3f0b4)

**Comment by mhughesacn** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 5 files pending identification.
* Protex Server Path: /Users/martin.hughes/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 1cf11562d591fd5e4a60bcf708426aa3f2493293

 **Report detail:** [gist](https://gist.github.com/51a08681e3b79757b49e1e4a092e4747)

**Comment by mhughesacn** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 5 files pending identification.
* Protex Server Path: /Users/martin.hughes/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 1cf11562d591fd5e4a60bcf708426aa3f2493293

 **Report detail:** [gist](https://gist.github.com/5fa3c8c3ce47ad938e31886c6f1d78dc)

**Comment by mhughesacn** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 5 files pending identification.
* Protex Server Path: /Users/martin.hughes/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 1cf11562d591fd5e4a60bcf708426aa3f2493293

 **Report detail:** [gist](https://gist.github.com/646da3345b9a50d053251d42ef2654e6)

**Comment by mhughesacn** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 5 files pending identification.
* Protex Server Path: /Users/martin.hughes/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 1cf11562d591fd5e4a60bcf708426aa3f2493293

 **Report detail:** [gist](https://gist.github.com/1d211361addd79981daf2ac69fcf00c2)

**Comment by mhughesacn** [comment]
## Blackduck scan failure details

**Summary**: 0 **violation**s, 0 files pending approval, 5 files pending identification.
* Protex Server Path: /Users/martin.hughes/github/sample-licensing/5/rdkcentral/sample-licensing

* Commit: 1cf11562d591fd5e4a60bcf708426aa3f2493293

 **Report detail:** [gist](https://gist.github.com/2837989bf8c76e90294f95d3289fbd2e)

**Pull request closed without merging**
